# create 1D array with alias as np and perform the following methods
#np.zeros()
#np.ones()
#np.empty()
#np.arange()
#np.reshape()
#np.linspace()



In [3]:

import numpy as np
first_numpy_array = np.array([1,2,3,4])
print (first_numpy_array)


[1 2 3 4]


In [5]:
pip install numpy



[notice] A new release of pip is available: 23.0.1 -> 23.1
[notice] To update, run: C:\Users\HP\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip



     ---------------------------------------- 14.8/14.8 MB 5.9 MB/s eta 0:00:00


In [4]:
#1
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#2
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#3
array_with_empty = np.empty((2,3))
array_with_empty

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [6.23047842e-307, 2.22526399e-307, 2.05837348e-312]])

In [8]:
np_arange = np.arange(12)
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
np_linspce = np.linspace(1,6,5)
np_linspce

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [12]:
oneD = np.arange(15)
oneD

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
twoD = oneD.reshape(3,5)
twoD

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [15]:
threeD = np.arange(27).reshape(3,3,3)
threeD

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [16]:
import numpy as np

In [17]:
np.array(24)

array(24)

In [18]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [20]:
np.array([[1,1,1],[1,2,1]])

array([[1, 1, 1],
       [1, 2, 1]])

In [23]:
numpy_arr = np.array([[[1,1,1],[2,2,2]],[[3,3,3],[4,4,4]]])

In [24]:
numpy_arr.shape

(2, 2, 3)

In [27]:
numpy_arr1 = np.array([x for x in range(1,10)])
numpy_arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
numpy_arr1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
numpy_arr1 =  np.array([x for x in range(1,13)])
numpy_arr1.reshape(2,2,3)
numpy_arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [33]:
numpy_arr1.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# arithematic operations

In [53]:
import numpy as np
A = np.array([[1,2,1], [2,2,3]])
B = np.array([3,4,5])


In [36]:
A

array([[1, 2, 1],
       [2, 2, 3]])

In [37]:
B

array([3, 4, 5])

In [39]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [41]:
np.subtract(B,A)

array([[2, 2, 4],
       [1, 2, 2]])

In [43]:
np.multiply(A,B)

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [44]:
np.divide(A,B)

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [45]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]], dtype=int32)

np.power(A,B)

# conditional operations

In [52]:
import numpy as np
x = np.array([i for i in range(10)])
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.where(x%2==0, 'Even', 'Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd'], dtype='<U4')

In [50]:
condlist = [x<5, x>5]
choicelist = [x**2, x**3]

In [51]:
np.select(condlist,choicelist,default=x)

array([  0,   1,   4,   9,  16,   5, 216, 343, 512, 729])

# Common mathematical and statistical functions in Numpy

In [54]:
import numpy as np

In [55]:
arr = np.array([[4,3,2],[10,1,0],[5,8,24]])
arr

array([[ 4,  3,  2],
       [10,  1,  0],
       [ 5,  8, 24]])

In [56]:
np.amin(arr)

0

In [57]:
np.amin(arr, axis=0)

array([4, 1, 0])

In [58]:
np.max(arr)

24

In [60]:
np.amax(arr, axis=0)

array([10,  8, 24])

In [61]:
np.amax(arr, axis=1)

array([ 4, 10, 24])

In [62]:
np.median(arr)

4.0

In [63]:
np.mean(arr)

6.333333333333333

In [64]:
np.std(arr)

6.944222218666553

In [65]:
np.var(arr)

48.22222222222222

In [66]:
np.percentile(arr, 50)

4.0

In [67]:
deg = np.array([0,30,45,60,90])

In [68]:
np.sin(deg+np.pi/180)

array([ 0.01745241, -0.98518908,  0.85994206, -0.3213861 ,  0.88604054])

In [69]:
np.cos(deg+np.pi/180)

array([ 0.9998477 ,  0.17147149,  0.51039167, -0.94694824, -0.46360777])

In [70]:
np.tan(deg+np.pi/180)

array([ 0.01745506, -5.74549801,  1.68486697,  0.33939141, -1.91118572])

# Indexing and slicing

In [71]:
import numpy as np

In [76]:
arr1D = np.array([1,2,3,4,5,6])
arr2D = np.array([[1,2,3],[4,5,6]])
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9], [10,11,12]]])

In [77]:
arr1D [0]

1

In [81]:
arr2D[1,-1]

6

In [89]:
arr3D[1,1,-1]

12

In [90]:
arr1D[1:]

array([2, 3, 4, 5, 6])

In [92]:
arr1D[3:5]

array([4, 5])

In [93]:
arr2D[1,1:]

array([5, 6])

In [94]:
arr3D[0,1:,1:]

array([[5, 6]])